quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=dev
quarkus.datasource.password=dev
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/development

# SQL statement logging
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true
