jakarta.persistence.jdbc.url=jdbc:postgresql://db/development
jakarta.persistence.jdbc.user=dev
jakarta.persistence.jdbc.password=dev

# SQL statement logging
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true
